---kind:   - Troubleshootingproducts:    - Alauda Container Platform   - Alauda DevOps   - Alauda AI   - Alauda Application Services   - Alauda Service Mesh   - Alauda Developer PortalProductsVersion:   - 4.1.0,4.2.x---<!-- A type of document that involves encountering a fault, diag...it, performing root cause analysis, and providing solutions. --># kubekube-ovn-cni报错 docker运行时下的pod启动失败## Cause- 缺少SYS_PTRACE capability## Resolution- 在kube-ovn-cni daemonset中增加securityContext.capabilities.add: SYS_PTRACE## [workaround]- 设置kube-ovn-cni为特权模式## [Related Information]**Screenshots**![screenshot-2.png](https://jira.alauda.cn/secure/attachment/186762/screenshot-2.png)- Environment: CNI 1.12.21- kube-ovn-cni- docker runtime- SYS_PTRACE capability- daemonset配置- Component: Docker- Page ID: 228557140- Original Title: kube-ovn 权限问题导致docker  运行时下的pod 启动失败